package net.arnx.wmf2svg.gdi.wmf;

import java.io.File;
import java.io.FileOutputStream;
import java.io.UnsupportedEncodingException;

import net.arnx.wmf2svg.gdi.Gdi;
import net.arnx.wmf2svg.gdi.GdiBrush;
import net.arnx.wmf2svg.gdi.GdiFont;
import net.arnx.wmf2svg.gdi.GdiPalette;
import net.arnx.wmf2svg.gdi.GdiPatternBrush;
import net.arnx.wmf2svg.gdi.GdiPen;
import net.arnx.wmf2svg.gdi.GdiRegion;
import net.arnx.wmf2svg.gdi.Point;

public class FulltestWmfGenerator {
	private static final int W = 27940;
	private static final int H = 21590;

	public static void main(String[] args) throws Exception {
		File out = args.length > 0 ? new File(args[0]) : new File("src/test/data/wmf/fulltest.wmf");
		File parent = out.getParentFile();
		if (parent != null) {
			parent.mkdirs();
		}

		WmfGdi gdi = new WmfGdi();
		gdi.placeableHeader(0, 0, W, H, 2540);
		gdi.header();
		gdi.setMapMode(Gdi.MM_ANISOTROPIC);
		gdi.setWindowOrgEx(0, 0, null);
		gdi.setWindowExtEx(W, H, null);
		gdi.setViewportOrgEx(0, 0, null);
		gdi.setViewportExtEx(W, H, null);
		gdi.setBkMode(Gdi.TRANSPARENT);
		gdi.setTextColor(rgb(0, 0, 0));
		gdi.setBkColor(rgb(255, 255, 255));

		GdiFont titleFont = gdi.createFontIndirect(-420, 0, 0, 0, 700, false, false, false,
				GdiFont.ANSI_CHARSET, 0, 0, 0, 0, ascii("Arial"));
		GdiFont labelFont = gdi.createFontIndirect(-260, 0, 0, 0, 400, false, false, false,
				GdiFont.ANSI_CHARSET, 0, 0, 0, 0, ascii("Arial"));
		GdiFont monoFont = gdi.createFontIndirect(-220, 0, 0, 0, 400, false, false, false,
				GdiFont.ANSI_CHARSET, 0, 0, 0, 0, ascii("Courier New"));
		GdiFont italicFont = gdi.createFontIndirect(-260, 0, 0, 0, 400, true, false, false,
				GdiFont.ANSI_CHARSET, 0, 0, 0, 0, ascii("Times New Roman"));
		GdiFont underlineFont = gdi.createFontIndirect(-240, 0, 0, 0, 700, false, true, true,
				GdiFont.ANSI_CHARSET, 0, 0, 0, 0, ascii("Arial"));
		GdiFont rotateFont = gdi.createFontIndirect(-240, 0, 450, 450, 700, false, false, false,
				GdiFont.ANSI_CHARSET, 0, 0, 0, 0, ascii("Arial"));

		GdiPen nullPen = gdi.createPenIndirect(GdiPen.PS_NULL, 1, rgb(0, 0, 0));
		GdiPen black = gdi.createPenIndirect(GdiPen.PS_SOLID, 35, rgb(0, 0, 0));
		GdiPen thin = gdi.createPenIndirect(GdiPen.PS_SOLID, 20, rgb(0, 0, 0));
		GdiPen red = gdi.createPenIndirect(GdiPen.PS_SOLID, 55, rgb(220, 0, 0));
		GdiPen blue = gdi.createPenIndirect(GdiPen.PS_SOLID, 55, rgb(0, 0, 220));
		GdiPen green = gdi.createPenIndirect(GdiPen.PS_SOLID, 45, rgb(20, 135, 65));
		GdiPen dash = gdi.createPenIndirect(GdiPen.PS_DASH, 35, rgb(0, 0, 0));
		GdiPen dot = gdi.createPenIndirect(GdiPen.PS_DOT, 35, rgb(0, 0, 0));
		GdiPen dashDot = gdi.createPenIndirect(GdiPen.PS_DASHDOT, 35, rgb(0, 0, 0));
		GdiPen dashDotDot = gdi.createPenIndirect(GdiPen.PS_DASHDOTDOT, 35, rgb(0, 0, 0));
		GdiPen thickBlue = gdi.createPenIndirect(GdiPen.PS_SOLID, 95, rgb(0, 40, 220));

		GdiBrush white = gdi.createBrushIndirect(GdiBrush.BS_SOLID, rgb(255, 255, 255), 0);
		GdiBrush blackBrush = gdi.createBrushIndirect(GdiBrush.BS_SOLID, rgb(0, 0, 0), 0);
		GdiBrush paleBlue = gdi.createBrushIndirect(GdiBrush.BS_SOLID, rgb(184, 216, 240), 0);
		GdiBrush paleGreen = gdi.createBrushIndirect(GdiBrush.BS_SOLID, rgb(200, 230, 200), 0);
		GdiBrush paleRed = gdi.createBrushIndirect(GdiBrush.BS_SOLID, rgb(255, 204, 204), 0);
		GdiBrush yellow = gdi.createBrushIndirect(GdiBrush.BS_SOLID, rgb(255, 255, 0), 0);
		GdiBrush redBrush = gdi.createBrushIndirect(GdiBrush.BS_SOLID, rgb(255, 0, 0), 0);
		GdiBrush greenBrush = gdi.createBrushIndirect(GdiBrush.BS_SOLID, rgb(0, 128, 0), 0);
		GdiBrush blueBrush = gdi.createBrushIndirect(GdiBrush.BS_SOLID, rgb(0, 0, 255), 0);
		GdiBrush hollow = gdi.createBrushIndirect(GdiBrush.BS_HOLLOW, rgb(0, 0, 0), 0);
		GdiBrush hatchH = gdi.createBrushIndirect(GdiBrush.BS_HATCHED, rgb(0, 0, 0), GdiBrush.HS_HORIZONTAL);
		GdiBrush hatchV = gdi.createBrushIndirect(GdiBrush.BS_HATCHED, rgb(0, 0, 0), GdiBrush.HS_VERTICAL);
		GdiBrush hatchF = gdi.createBrushIndirect(GdiBrush.BS_HATCHED, rgb(0, 0, 0), GdiBrush.HS_FDIAGONAL);
		GdiBrush hatchB = gdi.createBrushIndirect(GdiBrush.BS_HATCHED, rgb(0, 0, 0), GdiBrush.HS_BDIAGONAL);
		GdiBrush hatchC = gdi.createBrushIndirect(GdiBrush.BS_HATCHED, rgb(0, 0, 0), GdiBrush.HS_CROSS);
		GdiBrush hatchD = gdi.createBrushIndirect(GdiBrush.BS_HATCHED, rgb(0, 0, 0), GdiBrush.HS_DIAGCROSS);
		GdiPatternBrush pattern = gdi.dibCreatePatternBrush(dib8Pattern(), Gdi.DIB_RGB_COLORS);

		gdi.selectObject(titleFont);
		gdi.textOut(550, 750, ascii("WMF GDI full command overview"));
		gdi.selectObject(labelFont);
		gdi.textOut(550, 1150, ascii("Generated by FulltestWmfGenerator: primitives, text, pens, brushes, regions, palettes, raster ops and DC state."));

		panel(gdi, black, white, 400, 1700, 6900, 5400, "1 primitives");
		gdi.selectObject(thin);
		gdi.selectObject(paleBlue);
		gdi.rectangle(1050, 2550, 2900, 3650);
		gdi.ellipse(3500, 2450, 5450, 3750);
		gdi.selectObject(hollow);
		gdi.roundRect(5750, 2250, 6600, 3850, 350, 350);
		gdi.selectObject(red);
		gdi.moveToEx(1050, 4550, null);
		gdi.lineTo(3050, 5100);
		gdi.selectObject(blue);
		gdi.polyline(new Point[] {p(3700, 5150), p(4450, 3950), p(5200, 5250), p(6150, 3800)});
		gdi.selectObject(green);
		gdi.polygon(new Point[] {p(5900, 3000), p(6600, 3600), p(6350, 4950), p(5500, 4600)});
		gdi.selectObject(black);
		gdi.setPixel(6600, 5050, rgb(0, 0, 0));

		panel(gdi, black, white, 7300, 1700, 13800, 5400, "2 arcs and fill modes");
		gdi.selectObject(thin);
		gdi.selectObject(hollow);
		gdi.arc(7900, 2400, 10000, 3900, 7900, 3150, 10000, 3150);
		gdi.selectObject(paleGreen);
		gdi.chord(10400, 2400, 12800, 3900, 10400, 3150, 12800, 3150);
		gdi.pie(7900, 3850, 10000, 5200, 7900, 4500, 10000, 4500);
		gdi.roundRect(10800, 4100, 13000, 5050, 500, 500);
		gdi.selectObject(paleRed);
		gdi.setPolyFillMode(Gdi.ALTERNATE);
		gdi.polygon(new Point[] {p(11800, 2050), p(12350, 3500), p(11000, 2550), p(12600, 2550), p(11250, 3500)});
		gdi.selectObject(paleBlue);
		gdi.setPolyFillMode(Gdi.WINDING);
		gdi.polygon(new Point[] {p(8400, 2050), p(8950, 3500), p(7600, 2550), p(9200, 2550), p(7850, 3500)});

		panel(gdi, black, white, 14200, 1700, 20800, 5400, "3 pens and ROP2");
		GdiPen[] pens = new GdiPen[] {black, dash, dot, dashDot, dashDotDot, thickBlue};
		String[] penNames = new String[] {"solid", "dash", "dot", "dash-dot", "dash-dot-dot", "wide"};
		for (int i = 0; i < pens.length; i++) {
			gdi.selectObject(pens[i]);
			gdi.moveToEx(15000, 2400 + i * 430, null);
			gdi.lineTo(19000, 2400 + i * 430);
			gdi.selectObject(labelFont);
			gdi.textOut(19300, 2310 + i * 430, ascii(penNames[i]));
		}
		gdi.selectObject(blue);
		gdi.setROP2(Gdi.R2_XORPEN);
		gdi.rectangle(15200, 4700, 16400, 5150);
		gdi.rectangle(17600, 4700, 18800, 5150);
		gdi.setROP2(Gdi.R2_COPYPEN);

		panel(gdi, black, white, 21200, 1700, 27500, 5400, "4 brushes");
		GdiBrush[] brushes = new GdiBrush[] {blackBrush, redBrush, greenBrush, blueBrush, yellow, hollow, hatchH, hatchV, hatchF, hatchB, hatchC, hatchD};
		for (int i = 0; i < brushes.length; i++) {
			int x = 21800 + (i % 5) * 1050;
			int y = 2500 + (i / 5) * 850;
			gdi.selectObject(thin);
			gdi.selectObject(brushes[i]);
			gdi.rectangle(x, y, x + 780, y + 560);
		}
		gdi.selectObject(thin);
		gdi.selectObject(pattern);
		gdi.rectangle(23900, 4200, 24680, 4760);
		gdi.selectObject(labelFont);
		gdi.textOut(21800, 5050, ascii("solid, hollow, hatch, DIB pattern"));

		panel(gdi, black, white, 400, 5850, 6900, 9600, "5 text records");
		gdi.selectObject(labelFont);
		gdi.setTextAlign(Gdi.TA_LEFT | Gdi.TA_TOP);
		gdi.textOut(850, 6700, ascii("TextOut left/top"));
		gdi.extTextOut(850, 7100, Gdi.ETO_OPAQUE, new int[] {800, 7000, 4300, 7450}, ascii("ExtTextOut opaque"), null);
		gdi.setTextCharacterExtra(35);
		gdi.textOut(850, 7700, ascii("character extra"));
		gdi.setTextCharacterExtra(0);
		gdi.setTextJustification(900, 2);
		gdi.textOut(850, 8150, ascii("text justification"));
		gdi.setTextJustification(0, 0);
		gdi.selectObject(italicFont);
		gdi.textOut(850, 8600, ascii("italic Times New Roman"));
		gdi.selectObject(underlineFont);
		gdi.textOut(850, 8900, ascii("underline + strikeout"));
		gdi.selectObject(rotateFont);
		gdi.textOut(4300, 8950, ascii("rotated 45deg"));
		gdi.selectObject(labelFont);
		gdi.setTextAlign(Gdi.TA_RIGHT | Gdi.TA_TOP);
		gdi.textOut(6600, 9050, ascii("right aligned"));
		gdi.setTextAlign(Gdi.TA_LEFT | Gdi.TA_TOP);

		panel(gdi, black, white, 7300, 5850, 13800, 9600, "6 clipping and regions");
		GdiRegion rgn = gdi.createRectRgn(7850, 6650, 10350, 8350);
		gdi.selectObject(paleGreen);
		gdi.fillRgn(rgn, paleGreen);
		gdi.frameRgn(rgn, blackBrush, 120, 120);
		gdi.seveDC();
		gdi.intersectClipRect(8000, 6750, 10100, 8150);
		gdi.selectObject(red);
		gdi.rectangle(7600, 6400, 10700, 8600);
		gdi.restoreDC(-1);
		gdi.seveDC();
		gdi.excludeClipRect(8750, 6700, 9550, 8350);
		gdi.selectObject(blue);
		gdi.ellipse(8000, 6550, 10500, 8550);
		gdi.restoreDC(-1);
		gdi.seveDC();
		gdi.selectClipRgn(rgn);
		gdi.offsetClipRgn(300, 0);
		gdi.selectObject(green);
		gdi.moveToEx(7600, 9050, null);
		gdi.lineTo(10800, 6250);
		gdi.restoreDC(-1);
		gdi.paintRgn(rgn);
		gdi.invertRgn(rgn);

		panel(gdi, black, white, 14200, 5850, 20800, 9600, "7 raster transfers");
		byte[] dib = dib24(32, 32);
		byte[] bitmap = wmfBitmap24(24, 24);
		gdi.bitBlt(bitmap, 14900, 6650, 900, 900, 0, 0, Gdi.SRCCOPY);
		gdi.stretchBlt(bitmap, 16200, 6500, 1200, 1000, 0, 0, 24, 24, Gdi.SRCCOPY);
		gdi.dibBitBlt(dib, 17600, 6650, 900, 900, 0, 0, Gdi.SRCCOPY);
		gdi.dibStretchBlt(dib, 18900, 6500, 1300, 1000, 0, 0, 32, 32, Gdi.SRCCOPY);
		gdi.setDIBitsToDevice(14900, 8000, 900, 900, 0, 0, 0, 32, dib, Gdi.DIB_RGB_COLORS);
		gdi.stretchDIBits(16200, 7900, 1500, 1100, 0, 0, 32, 32, dib, Gdi.DIB_RGB_COLORS, Gdi.SRCCOPY);
		gdi.selectObject(hatchC);
		gdi.patBlt(18300, 8000, 1700, 900, Gdi.PATCOPY);

		panel(gdi, black, white, 21200, 5850, 27500, 9600, "8 palette records");
		int[] paletteEntries = new int[] {rgb(255, 0, 0), rgb(0, 160, 0), rgb(0, 0, 255), rgb(255, 255, 0), rgb(255, 0, 255), rgb(0, 255, 255)};
		GdiBrush[] paletteSwatches = new GdiBrush[] {redBrush, greenBrush, blueBrush, yellow, blackBrush, paleBlue};
		gdi.selectObject(labelFont);
		gdi.textOut(21800, 6600, ascii("direct RGB swatches"));
		for (int i = 0; i < paletteSwatches.length; i++) {
			gdi.selectObject(thin);
			gdi.selectObject(paletteSwatches[i]);
			gdi.rectangle(21800 + i * 850, 6800, 22450 + i * 850, 7550);
		}

		GdiPalette palette = gdi.createPalette(0x300, paletteEntries);
		gdi.selectPalette(palette, false);
		gdi.realizePalette();
		gdi.resizePalette(palette, 8);
		gdi.setPaletteEntries(palette, 0, new int[] {rgb(128, 0, 0), rgb(0, 128, 0), rgb(0, 0, 128), rgb(128, 128, 0)});
		gdi.animatePalette(palette, 0, paletteEntries);

		gdi.selectObject(thin);
		gdi.selectObject(hollow);
		gdi.rectangle(21800, 8000, 26800, 8750);
		gdi.selectObject(labelFont);
		gdi.textOut(22050, 8120, ascii("records: create/select/resize/set"));
		gdi.textOut(22050, 8450, ascii("animate/realize palette"));

		panel(gdi, black, white, 400, 10050, 9200, 14200, "9 mapping and DC state");
		gdi.selectObject(blue);
		gdi.moveToEx(950, 11000, null);
		gdi.lineTo(8500, 12400);
		gdi.seveDC();
		gdi.offsetWindowOrgEx(-1400, -700, null);
		gdi.selectObject(red);
		gdi.rectangle(1000, 11800, 3300, 13200);
		gdi.restoreDC(-1);
		gdi.seveDC();
		gdi.offsetViewportOrgEx(2500, 1300, null);
		gdi.selectObject(green);
		gdi.ellipse(1000, 11800, 3300, 13200);
		gdi.restoreDC(-1);
		gdi.scaleWindowExtEx(1, 1, 1, 1, null);
		gdi.scaleViewportExtEx(1, 1, 1, 1, null);
		gdi.setMapperFlags(1);
		gdi.setStretchBltMode(Gdi.COLORONCOLOR);
		gdi.setRelAbs(Gdi.ABSOLUTE);
		gdi.escape(ascii("WMF escape test payload"));

		panel(gdi, black, white, 9600, 10050, 18400, 14200, "10 object lifecycle");
		GdiBrush tempBrush = gdi.createBrushIndirect(GdiBrush.BS_SOLID, rgb(208, 208, 208), 0);
		GdiPen tempPen = gdi.createPenIndirect(GdiPen.PS_SOLID, 70, rgb(255, 128, 0));
		gdi.selectObject(tempPen);
		gdi.selectObject(tempBrush);
		gdi.rectangle(10300, 11100, 12600, 12300);
		gdi.deleteObject(tempBrush);
		gdi.selectObject(hollow);
		gdi.rectangle(13100, 11100, 15400, 12300);
		gdi.deleteObject(tempPen);
		gdi.selectObject(black);
		gdi.selectObject(monoFont);
		gdi.textOut(10300, 13200, ascii("create/select/delete object"));

		panel(gdi, black, white, 18800, 10050, 27500, 14200, "11 stress: many records");
		for (int i = 0; i < 18; i++) {
			gdi.selectObject(thin);
			gdi.selectObject(hollow);
			int x = 19400 + i * 430;
			int y = 10900 + i * 120;
			gdi.rectangle(x, y, x + 1200, y + 900);
		}
		for (int i = 0; i < 10; i++) {
			gdi.selectObject(paleBlue);
			int x = 21200 + (i % 5) * 1100;
			int y = 11100 + (i / 5) * 980;
			gdi.ellipse(x, y, x + 700, y + 700);
		}
		gdi.selectObject(paleGreen);
		gdi.polygon(new Point[] {p(19500, 13400), p(21000, 12150), p(22500, 13400), p(24200, 12000), p(26000, 13550)});
		gdi.selectObject(red);
		gdi.moveToEx(19300, 13700, null);
		gdi.lineTo(27000, 11000);
		gdi.selectObject(blue);
		gdi.moveToEx(19300, 10900, null);
		gdi.lineTo(27000, 13700);
		gdi.selectObject(labelFont);
		gdi.textOut(19300, 13900, ascii("overlapping primitives, text, bitmap and palette records"));

		try (FileOutputStream fos = new FileOutputStream(out)) {
			gdi.write(fos);
		}
	}

	private static void panel(WmfGdi gdi, GdiPen pen, GdiBrush brush, int x1, int y1, int x2, int y2, String label) {
		gdi.selectObject(pen);
		gdi.selectObject(brush);
		gdi.rectangle(x1, y1, x2, y2);
		gdi.selectObject(brush);
		gdi.textOut(x1 + 250, y1 + 520, ascii(label));
	}

	private static Point p(int x, int y) {
		return new Point(x, y);
	}

	private static int rgb(int r, int g, int b) {
		return (b << 16) | (g << 8) | r;
	}

	private static byte[] ascii(String s) {
		try {
			return s.getBytes("US-ASCII");
		} catch (UnsupportedEncodingException e) {
			return new byte[0];
		}
	}

	private static byte[] dib24(int width, int height) {
		int stride = ((width * 3 + 3) / 4) * 4;
		byte[] dib = new byte[40 + stride * height];
		setInt(dib, 0, 40);
		setInt(dib, 4, width);
		setInt(dib, 8, height);
		setShort(dib, 12, 1);
		setShort(dib, 14, 24);
		setInt(dib, 20, stride * height);
		for (int y = 0; y < height; y++) {
			for (int x = 0; x < width; x++) {
				int topY = height - 1 - y;
				int pos = 40 + y * stride + x * 3;
				boolean checker = ((x / 4) + (topY / 4)) % 2 == 0;
				dib[pos] = (byte)(checker ? 220 : 60);
				dib[pos + 1] = (byte)(x * 255 / Math.max(1, width - 1));
				dib[pos + 2] = (byte)(topY * 255 / Math.max(1, height - 1));
			}
		}
		return dib;
	}

	private static byte[] dib8Pattern() {
		int width = 8;
		int height = 8;
		int stride = 8;
		byte[] dib = new byte[40 + 256 * 4 + stride * height];
		setInt(dib, 0, 40);
		setInt(dib, 4, width);
		setInt(dib, 8, height);
		setShort(dib, 12, 1);
		setShort(dib, 14, 8);
		setInt(dib, 20, stride * height);
		setInt(dib, 32, 256);
		for (int i = 0; i < 256; i++) {
			setInt(dib, 40 + i * 4, rgb(i, 0, 0));
		}
		for (int y = 0; y < height; y++) {
			for (int x = 0; x < width; x++) {
				dib[40 + 256 * 4 + y * stride + x] = (byte)((x + y) * 16);
			}
		}
		return dib;
	}

	private static byte[] wmfBitmap24(int width, int height) {
		int stride = ((width * 3 + 1) / 2) * 2;
		byte[] bitmap = new byte[10 + stride * height];
		setShort(bitmap, 0, 0);
		setShort(bitmap, 2, width);
		setShort(bitmap, 4, height);
		setShort(bitmap, 6, stride);
		bitmap[8] = 1;
		bitmap[9] = 24;
		for (int y = 0; y < height; y++) {
			for (int x = 0; x < width; x++) {
				int pos = 10 + y * stride + x * 3;
				boolean checker = ((x / 4) + (y / 4)) % 2 == 0;
				bitmap[pos] = (byte)(checker ? 240 : 80);
				bitmap[pos + 1] = (byte)(255 - x * 255 / Math.max(1, width - 1));
				bitmap[pos + 2] = (byte)(y * 255 / Math.max(1, height - 1));
			}
		}
		return bitmap;
	}

	private static void setShort(byte[] data, int pos, int value) {
		data[pos] = (byte)(value & 0xFF);
		data[pos + 1] = (byte)((value >>> 8) & 0xFF);
	}

	private static void setInt(byte[] data, int pos, int value) {
		data[pos] = (byte)(value & 0xFF);
		data[pos + 1] = (byte)((value >>> 8) & 0xFF);
		data[pos + 2] = (byte)((value >>> 16) & 0xFF);
		data[pos + 3] = (byte)((value >>> 24) & 0xFF);
	}
}
